### ISSUE TITLE
ailed resolution of: Lcom/clockbyte/admobadapter/AdmobFetcher$2; version 1.4.6 previously same code worked fine

### ISSUE THREAD

**Issue by devasish11** [clockbyte/admobadapter#140]
Version 1.4.6

compilesdk ver 31

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/clockbyte/admobadapter/AdmobFetcher$2;
        at com.clockbyte.admobadapter.AdmobFetcher.setupAds(AdmobFetcher.java:225)
        at com.clockbyte.admobadapter.AdmobFetcher.prefetchAds(AdmobFetcher.java:106)
        at com.clockbyte.admobadapter.AdmobAdapterWrapper.init(AdmobAdapterWrapper.java:306)
        at com.clockbyte.admobadapter.AdmobAdapterWrapper.<init>(AdmobAdapterWrapper.java:252)
        at com.clockbyte.admobadapter.AdmobAdapterWrapper.<init>(AdmobAdapterWrapper.java:204)
        at babu.accidentlawyer.SearchActivity.onCreate(SearchActivity.java:245)

  adapter = new SimpleAdapter(SearchActivity.this,itemDataList, android.R.layout.simple_list_item_2, new String[]{"name","address"}, new int[]{android.R.id.text1,android.R.id.text2});
              adapterWrapper = new AdmobAdapterWrapper(SearchActivity.this,getString(R.string.advanced_native ));

Before it was working fine, today I have updated all the gradle deps and changed the calls for google ads Init, everything works fine, but this line causes error and crash, it is also not showing the list with adverts.

**Comment by kot331107** [comment]
have you tried bump it to version 1.5.0?
